### ISSUE TITLE
Typer - Centered text issue + Feature request

### ISSUE THREAD

**Issue by CoolZoomer** [kartikfire/kartikfire.github.io#1]
**Issue:** when you center text and save it, after loading it, doesn't load the centered format.
**Feature request:** make it so that when you select some text then press "alt +", and it makes the selected text bigger and vice versa for "alt -".

**Comment by kartikfire** [comment]
@CoolZoomer Thanks for the bug and suggestion. I will add it soon!

**Comment by kartikfire** [comment]
Have fixed & added the feature, you can increase / decrease the text by ctrl ] & ctrl [
Thanks again for the bug and suggestion.
